name: CI

on:
  pull_request:
    branches: 
      - develop
      - master

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Make dictu and run tests
      run: |
        make debug
        ./dictu tests/runTests.du
